<?php
namespace App\Controller;

use App\Entity\Business;use App\Entity\Category;use App\Entity\Customer;use App\Entity\FiscalComponent;use App\Entity\FiscalRule;use App\Entity\FiscalRuleAuditLog;use App\Entity\Product;use App\Entity\Sale;use App\Entity\SaleItem;use App\Entity\User;
use App\Repository\CategoryRepository;use App\Repository\CustomerRepository;use App\Repository\FiscalRuleAuditLogRepository;use App\Repository\FiscalRuleRepository;use App\Repository\ProductRepository;use App\Security\BusinessContext;use App\Service\FiscalEngine;
use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\HttpFoundation\Response;use Symfony\Component\Routing\Annotation\Route;use Symfony\Component\Security\Core\Exception\AccessDeniedException;use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/app/admin/fiscal-rules', name: 'app_fiscal_rule_')] #[IsGranted('BUSINESS_ADMIN')]
class FiscalRuleController extends AbstractController
{
public function __construct(private readonly EntityManagerInterface $em,private readonly BusinessContext $businessContext,private readonly ProductRepository $productRepository,private readonly CategoryRepository $categoryRepository,private readonly CustomerRepository $customerRepository,private readonly FiscalEngine $fiscalEngine){}
#[Route('', name:'index', methods:['GET'])] public function index(FiscalRuleRepository $r): Response { $b=$this->businessContext->requireCurrentBusiness(); return $this->render('fiscal_rule/index.html.twig',['rules'=>$r->findForAdminList($b),'componentTypeLabels'=>$this->componentTypeLabels(),'appliesToLabels'=>$this->appliesToLabels(),'today'=>(new \DateTimeImmutable('today'))]); }
#[Route('/audit', name:'audit', methods:['GET'])] public function audit(Request $request, FiscalRuleAuditLogRepository $repo): Response { $b=$this->businessContext->requireCurrentBusiness(); $from=$request->query->get('from'); $to=$request->query->get('to'); $action=$request->query->get('action')?:null; $logs=$repo->findForAudit($b,$from?new \DateTimeImmutable($from.' 00:00:00'):null,$to?new \DateTimeImmutable($to.' 23:59:59'):null,$action); return $this->render('fiscal_rule/audit.html.twig',['logs'=>$logs,'from'=>$from,'to'=>$to,'action'=>$action]); }
#[Route('/simulator', name:'simulator', methods:['GET','POST'])] public function simulator(Request $request): Response { $b=$this->businessContext->requireCurrentBusiness(); $products=$this->productRepository->findBy(['business'=>$b,'isActive'=>true],['name'=>'ASC']); $customers=$this->customerRepository->findBy(['business'=>$b],['name'=>'ASC']); $result=null; if($request->isMethod('POST')){ $sale=(new Sale())->setBusiness($b); $c=$this->customerRepository->find((int)$request->request->get('customerId',0)); if($c instanceof Customer && $c->getBusiness()?->getId()===$b->getId()) $sale->setCustomer($c); foreach([1,2] as $n){$pid=(int)$request->request->get('product'.$n,0);$qty=(float)$request->request->get('qty'.$n,0); if($pid>0&&$qty>0){$p=$this->productRepository->find($pid); if($p instanceof Product && $p->getBusiness()?->getId()===$b->getId()){ $price=(string)$p->getPrice(); $line=number_format(((float)$price)*$qty,2,'.',''); $it=(new SaleItem())->setProduct($p)->setDescription($p->getName())->setQty(number_format($qty,3,'.',''))->setUnitPrice(number_format((float)$price,2,'.',''))->setLineSubtotal($line)->setLineDiscount('0.00')->setLineTotal($line); $sale->addItem($it); } } } $subtotal='0.00'; foreach($sale->getItems() as $i){$subtotal=bcadd($subtotal,$i->getLineTotal(),2);} $sale->setSubtotal($subtotal)->setDiscountTotal('0.00')->setTotal($subtotal); $result=$this->fiscalEngine->calculateForSale($b,$sale,[]);} return $this->render('fiscal_rule/simulator.html.twig',['products'=>$products,'customers'=>$customers,'result'=>$result]); }
#[Route('/new', name:'new', methods:['GET','POST'])] public function new(Request $q): Response { $b=$this->businessContext->requireCurrentBusiness(); return $this->upsert($q,(new FiscalRule())->setBusiness($b),$b);} #[Route('/{id}/edit', name:'edit', methods:['GET','POST'])] public function edit(Request $q, FiscalRule $rule): Response { $b=$this->businessContext->requireCurrentBusiness(); $this->assertRuleBelongsToBusiness($rule,$b); return $this->upsert($q,$rule,$b);} 
#[Route('/{id}/toggle', name:'toggle', methods:['POST'])] public function toggle(Request $request, FiscalRule $rule): Response { $b=$this->businessContext->requireCurrentBusiness(); $this->assertRuleBelongsToBusiness($rule,$b); if(!$this->isCsrfTokenValid('fiscal_rule_toggle_'.$rule->getId(),(string)$request->request->get('_token'))) throw new AccessDeniedException('CSRF inválido.'); $before=$rule->toAuditArray(); $rule->setActive(!$rule->isActive()); $this->logAudit($b,$rule,FiscalRuleAuditLog::ACTION_TOGGLED,$before,$rule->toAuditArray()); $this->em->flush(); return $this->redirectToRoute('app_fiscal_rule_index'); }
#[Route('/{id}/delete', name:'delete', methods:['POST'])] public function delete(Request $request, FiscalRule $rule): Response { $b=$this->businessContext->requireCurrentBusiness(); $this->assertRuleBelongsToBusiness($rule,$b); if(!$this->isCsrfTokenValid('fiscal_rule_delete_'.$rule->getId(),(string)$request->request->get('_token'))) throw new AccessDeniedException('CSRF inválido.'); $this->logAudit($b,$rule,FiscalRuleAuditLog::ACTION_DELETED,$rule->toAuditArray(),null); $this->em->remove($rule); $this->em->flush(); return $this->redirectToRoute('app_fiscal_rule_index'); }
private function upsert(Request $request, FiscalRule $rule, Business $business): Response { $products=$this->productRepository->findBy(['business'=>$business,'isActive'=>true],['name'=>'ASC']); $categories=$this->categoryRepository->findBy(['business'=>$business],['name'=>'ASC']); $customers=$this->customerRepository->findBy(['business'=>$business],['name'=>'ASC']); $isEdit=$rule->getId()!==null; if($request->isMethod('POST')){ if(!$this->isCsrfTokenValid($isEdit?'fiscal_rule_edit_'.$rule->getId():'fiscal_rule_new',(string)$request->request->get('_token'))) throw new AccessDeniedException('CSRF inválido.'); $before=$rule->toAuditArray(); try{$this->hydrateRule($rule,$request,$business); $errors=$this->validateRule($rule); if($errors){foreach($errors as $e)$this->addFlash('danger',$e);} else {$this->em->persist($rule); $this->logAudit($business,$rule,$isEdit?FiscalRuleAuditLog::ACTION_UPDATED:FiscalRuleAuditLog::ACTION_CREATED,$isEdit?$before:null,$rule->toAuditArray()); $this->em->flush(); if($rule->isReportToArca() && $rule->getApplicationMode()===FiscalRule::APPLICATION_MODE_APPLY && $rule->getArcaTributeId()===null){$this->addFlash('warning','Esta regla informa a ARCA pero no tiene código de tributo. La venta podrá fallar al facturar.');} return $this->redirectToRoute('app_fiscal_rule_index');}}catch(\Throwable $e){$this->addFlash('danger',$e->getMessage());}}
return $this->render('fiscal_rule/form.html.twig',['rule'=>$rule,'products'=>$products,'categories'=>$categories,'customers'=>$customers,'componentTypeLabels'=>$this->componentTypeLabels(),'appliesToLabels'=>$this->appliesToLabels(),'taxableBaseModeLabels'=>$this->taxableBaseModeLabels(),'applicationModes'=>[FiscalRule::APPLICATION_MODE_APPLY=>'Aplicar automáticamente',FiscalRule::APPLICATION_MODE_SUGGEST=>'Solo sugerir'],'ivaConditionOptions'=>[1=>'Responsable Inscripto',5=>'Consumidor Final',6=>'Responsable Monotributo',4=>'IVA Sujeto Exento']]); }
private function logAudit(Business $b,FiscalRule $r,string $a,?array $before,?array $after): void { try{$u=$this->getUser(); $log=(new FiscalRuleAuditLog())->setBusiness($b)->setFiscalRule($r)->setUser($u instanceof User?$u:null)->setAction($a)->setRuleName($r->getName())->setBeforeData($before)->setAfterData($after); $this->em->persist($log);}catch(\Throwable){} }
private function hydrateRule(FiscalRule $rule, Request $request, Business $business): void { $d=$request->request; $rule->setName((string)$this->emptyToNull($d->get('name')))->setActive($this->parseBool($d->get('active')))->setPriority((int)$d->get('priority',100))->setComponentType((string)$d->get('componentType',FiscalComponent::TYPE_OTHER))->setAppliesTo((string)$d->get('appliesTo',FiscalRule::APPLIES_TO_GLOBAL))->setJurisdiction($this->emptyToNull($d->get('jurisdiction')))->setDescriptionTemplate($this->emptyToNull($d->get('descriptionTemplate')))->setTaxableBaseMode((string)$d->get('taxableBaseMode',FiscalRule::TAXABLE_BASE_SALE_NET))->setApplicationMode((string)$d->get('applicationMode',FiscalRule::APPLICATION_MODE_APPLY))->setRate($this->decimalOrNull($d->get('rate'),4))->setFixedAmount($this->decimalOrNull($d->get('fixedAmount'),2))->setMinAmount($this->decimalOrNull($d->get('minAmount'),2))->setMaxAmount($this->decimalOrNull($d->get('maxAmount'),2))->setArcaTributeId($this->emptyToNull($d->get('arcaTributeId'))!==null?(int)$d->get('arcaTributeId'):null)->setReportToArca($this->parseBool($d->get('reportToArca')))->setAffectsTotal($this->parseBool($d->get('affectsTotal')))->setIncludedInPrice($this->parseBool($d->get('includedInPrice')))->setStopProcessing($this->parseBool($d->get('stopProcessing')))->setStartsAt($this->dateOrNull($d->get('startsAt')))->setEndsAt($this->dateOrNull($d->get('endsAt'))); }
private function validateRule(FiscalRule $rule): array { $e=[]; if(trim($rule->getName())==='')$e[]='El nombre es obligatorio.'; if($rule->getRate()===null&&$rule->getFixedAmount()===null)$e[]='Indicá alícuota o monto fijo.'; return $e; }
private function assertRuleBelongsToBusiness(FiscalRule $rule, Business $business): void { if($rule->getBusiness()?->getId()!==$business->getId()) throw new AccessDeniedException('No tenés acceso a esta regla fiscal.'); }
private function parseBool(mixed $value): bool { return in_array($value,['1',1,true,'true','on','yes','si','sí'],true);} private function emptyToNull(mixed $value): ?string { $value=is_string($value)?trim($value):$value; return $value===''||$value===null?null:(string)$value;} private function decimalOrNull(mixed $value,int $scale): ?string { $value=$this->emptyToNull($value); if($value===null)return null; $value=str_replace(',','.',$value); if(!is_numeric($value)||(float)$value<0) throw new \InvalidArgumentException('Importe o alícuota inválida.'); return number_format((float)$value,$scale,'.',''); } private function dateOrNull(mixed $value): ?\DateTimeInterface { $v=$this->emptyToNull($value); return $v?new \DateTimeImmutable($v):null; }
private function componentTypeLabels(): array { return [FiscalComponent::TYPE_INTERNAL_TAX=>'Impuestos internos',FiscalComponent::TYPE_IIBB_PERCEPTION=>'Percepción Ingresos Brutos',FiscalComponent::TYPE_VAT_PERCEPTION=>'Percepción IVA',FiscalComponent::TYPE_MUNICIPAL_TAX=>'Tasa municipal',FiscalComponent::TYPE_NATIONAL_OTHER_TAX=>'Otro impuesto nacional',FiscalComponent::TYPE_OTHER=>'Otro']; }
private function appliesToLabels(): array { return [FiscalRule::APPLIES_TO_GLOBAL=>'Global',FiscalRule::APPLIES_TO_PRODUCT=>'Producto',FiscalRule::APPLIES_TO_CATEGORY=>'Categoría',FiscalRule::APPLIES_TO_CUSTOMER=>'Cliente',FiscalRule::APPLIES_TO_CUSTOMER_IVA_CONDITION=>'Condición IVA cliente']; }
private function taxableBaseModeLabels(): array { return [FiscalRule::TAXABLE_BASE_SALE_NET=>'Neto de venta',FiscalRule::TAXABLE_BASE_SALE_TOTAL=>'Total de venta',FiscalRule::TAXABLE_BASE_ITEM_NET=>'Neto de ítems alcanzados',FiscalRule::TAXABLE_BASE_MANUAL_BASE=>'Base manual / monto fijo']; }
}
